# Generated by Django 3.2.5 on 2022-08-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220812_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_threads', to='api.topic'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
