# Generated by Django 3.2.5 on 2022-08-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_thread_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='topic',
            field=models.CharField(choices=[('1', 'Entertainment'), ('2', 'Sports'), ('3', 'Gaming'), ('4', 'Music'), ('5', 'Technology'), ('6', 'News'), ('7', 'Anime'), ('8', 'Drama & Movie')], default=1, max_length=32),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
