# Generated by Django 3.2.5 on 2022-08-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_thread_replynum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='replyNum',
            new_name='replyCount',
        ),
    ]
