# Generated by Django 3.2.5 on 2022-08-16 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_replynum_thread_replycount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='pinned',
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_pin', to='api.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pin', to=settings.AUTH_USER_MODEL, verbose_name='pinned by')),
            ],
        ),
    ]
